# Generated by Django 4.2.29 on 2026-04-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
